### ISSUE TITLE
定时启动有问题，不能按照设定的时间启动

### ISSUE THREAD

**Issue by Jjybub** [JunzhouLiu/bilibili-match-prediction#11]
设定的utc时间是25 0 * * *  延迟13分钟，到达预定时间时候没有按时启动，更改过两次时间也是同样的情况，不按照设定的时间启动执行。上面都是基于fork的最新的程序。
希望可以测试一下，

**Comment by JunzhouLiu** [comment]
这个启动确实存在延时的可能，原因是使用GitHub的机器执行定时任务时，部分时间段任务队列排的比较长，导致了启动会延迟，一般延迟20分钟-2个小时左右，但是这个问题是GitHub actions导致的，我这边没办法解决。
