### ISSUE TITLE
Error:  Failed to execute goal org.codehaus.mojo:exec-maven-plugin:3.0.0:java (default-cli) on project bilibili-match-prediction: An exception occured while executing the Java class. Not a JSON Object: null -> [Help 1] Error:   Error:  To see the full stack trace of the errors, re-run Maven with the -e switch. Error:  Re-run Maven using the -X switch to enable full debug logging. Error:   Error:  For more information about the errors and possible solutions, please read the following articles: Error:  [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException Error: Process completed with exit code 1.

### ISSUE THREAD

**Issue by FlynnClaudia** [JunzhouLiu/bilibili-match-prediction#15]
Error:  Failed to execute goal org.codehaus.mojo:exec-maven-plugin:3.0.0:java (default-cli) on project bilibili-match-prediction: An exception occured while executing the Java class. Not a JSON Object: null -> [Help 1]
Error:  
Error:  To see the full stack trace of the errors, re-run Maven with the -e switch.
Error:  Re-run Maven using the -X switch to enable full debug logging.
Error:  
Error:  For more information about the errors and possible solutions, please read the following articles:
Error:  [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
Error: Process completed with exit code 1.

**Comment by zhuweitung** [comment]
我是每天早上10点执行，也是报这个错
`Warning:  
java.lang.IllegalStateException: Not a JSON Object: null
    at com.google.gson.JsonElement.getAsJsonObject (JsonElement.java:91)
    at top.misec.task.UserCheck.run (UserCheck.java:30)
    at top.misec.task.DailyTask.doDailyTask (DailyTask.java:30)
    at top.misec.Main.main (Main.java:38)
    at org.codehaus.mojo.exec.ExecJavaMojo$1.run (ExecJavaMojo.java:254)
    at java.lang.Thread.run (Thread.java:748)`

**Comment by FlynnClaudia** [comment]
顶，楼上说的没错，的确是需要手动执行一次预测，脚本就正常了，感谢作者的付出，此帖终结。
