### ISSUE TITLE
运行出错，可尝试手动预测一轮。之后再执行。

### ISSUE THREAD

**Issue by yukiryo** [JunzhouLiu/bilibili-match-prediction#2]
[1_start.txt](https://github.com/JunzhouLiu/bilibili-match-prediction/files/6170979/1_start.txt)
日志

**Comment by msylgj** [comment]
进入赛事页面随便预测一场之后再运行action就好了, 看源码应该是从来没有参与过的时候从页面拉取jsondata为空,导致报错. 加入null判断会好一点 @JunzhouLiu

**Comment by JunzhouLiu** [comment]
> 进入赛事页面随便预测一场之后再运行action就好了, 看源码应该是从来没有参与过的时候从页面拉取jsondata为空,导致报错. 加入null判断会好一点 @JunzhouLiu

是的 存在这个可能，我只判断了返回的赛事列表是否为null。
