### ISSUE TITLE
钉钉推送报错，好像是什么utf-8编码不正确？

### ISSUE THREAD

**Issue by BillScott1024** [JunzhouLiu/bilibili-match-prediction#20]
钉钉推送报错，好像是什么utf-8编码不正确？

**{"errcode":300001,"errmsg":"param error"}**

![image](https://user-images.githubusercontent.com/22955480/113848447-0ef49f80-97cb-11eb-859d-89aeaa9cb030.png)

![image](https://user-images.githubusercontent.com/22955480/113848347-f3899480-97ca-11eb-93a4-a4f65230260c.png)

_Originally posted by @BillScott1024 in https://github.com/JunzhouLiu/bilibili-match-prediction/issues/17#issuecomment-814782808_

**Comment by JunzhouLiu** [comment]
@BillScott1024 解决了，应该是工具类里设置请求头`application/json`被覆盖为`application/x-www-form-urlencoded`导致的

**Comment by BillScott1024** [comment]
> @BillScott1024 解决了，应该是工具类里设置请求头`application/json`被覆盖为`application/x-www-form-urlencoded`导致的

好的，明天看下推送结果，没问题我就close issue了

**Comment by BillScott1024** [comment]
已解决
