### ISSUE TITLE
关于 README 的问题

### ISSUE THREAD

**Issue by start0325** [JunzhouLiu/bilibili-match-prediction#27]
https://github.com/start0325/bilibili-match-prediction#%E4%B8%89%E4%BD%BF%E7%94%A8-linux-crontab-%E6%96%B9%E5%BC%8F

请问是输入什么命令？这里空缺了一段。

另外，Linux Crontab 的序号是 `三`，Actions 的序号是 `一`，所以`二` 呢？

还有 `查看 Actions 运行日志` 的内容也是戛然而止……

实在太奇怪了。

**Comment by JunzhouLiu** [comment]
文档这块可参考https://github.com/JunzhouLiu/BILIBILI-HELPER项目，基础内容大致一样，目前预测助手比较简陋。

**Comment by start0325** [comment]
好的
