### ISSUE TITLE
胜率每况愈下，顶不住了。。

### ISSUE THREAD

**Issue by qilin008** [JunzhouLiu/bilibili-match-prediction#28]

**Comment by qilin008** [comment]
感觉反向预测能赢。。

**Comment by 1299172402** [comment]
其实按照现在的概率，每天只要有输一局，就大约要赢回5局才可以保本。。。。所以如果现在这样随时间的增长，亏硬币是必然的。。。。除非能每天每局都压对才能赢硬币。。。。

**Comment by JunzhouLiu** [comment]
> 其实按照现在的概率，每天只要有输一局，就大约要赢回5局才可以保本。。。。所以如果现在这样随时间的增长，亏硬币是必然的。。。。除非能每天每局都压对才能赢硬币。。。。

守望先锋系列的赛事 如果按照胜率下压 大概率要赔，英雄联盟的赛事倒是没太大问题。
