### ISSUE TITLE
Failed to add secret. Name is invalid

### ISSUE THREAD

**Issue by cy920820** [JunzhouLiu/bilibili-match-prediction#3]
### 错误描述
使用 workflow 中自动同步上游代码库时，添加必要的 `GITHUB_TOKEN` env 时系统报错

### 错误提示和日志内容
错误信息：Failed to add secret. Name is invalid

### 使用的版本信息
当前最新版本 v1.0.3

### 使用环境
Actions

**Comment by JunzhouLiu** [comment]
建议使用pull app同步代码
