### ISSUE TITLE
不知可否加个赔率判断，大于多少赔率的才压，虽然赚的少，但是比较稳。。

### ISSUE THREAD

**Issue by qilin7** [JunzhouLiu/bilibili-match-prediction#8]
还可以加个自定义队伍列表，压自己喜欢的队伍，无视赔率。。

**Comment by JunzhouLiu** [comment]
实践证明，在kpl赛事中，经常出现7倍赔率的获胜，后续会考虑探索更合理的预测方式😅

其实最大的问题，就是赔率并不能很直观的反映这个场次的胜率，有的队伍可能上的队员都是非主力队员。

**Comment by qilin7** [comment]
淦，真的狗。。
