### ISSUE TITLE
每隔一到两个小时就自动启动一次

### ISSUE THREAD

**Issue by Jjybub** [JunzhouLiu/bilibili-match-prediction#9]
1、按照格式设置定时运行的时间了，但是没有用，总是自己每隔一两个小时就自己运行一次。
2、1.0.5的trigger文件还存在，还需不需要设置没有说明，测试不设置的话程序不能自动运行。
3、sever酱的sckey并不是你说的在secrests中添加的name为serverpushkey，而是一开始的SCKEY，说明地方有点前后矛盾，搞不清楚。

**Comment by JunzhouLiu** [comment]
1. 如果actions 2小时执行一次请检查cron表达式是否正确。
2. 新文档启用的server酱的key是SCKEY，bilibili-helper的key则是serverpushkey。
3. tagger.json无需修改，按照文档将skip dailytask值改为false即可。

**Comment by JunzhouLiu** [comment]
文档描述不一致的地方，我晚上修改一下，文档这块暂时比较粗糙。
